## 1. How likely is it that you roll doubles when rolling two dice?

In [71]:
import numpy as np
import pandas as pd

In [42]:
n_trials = nrows = 10_000
n_dice = ncols = 1

rolls1 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls1


array([[2],
       [4],
       [3],
       ...,
       [5],
       [6],
       [3]])

In [43]:
n_trials = nrows = 10_000
n_dice = ncols = 1

rolls2 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls2

array([[1],
       [6],
       [6],
       ...,
       [2],
       [5],
       [4]])

In [45]:
(rolls1 == rolls2).mean()

0.1638

In [46]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls3 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls3

array([[2, 5],
       [2, 2],
       [3, 1],
       ...,
       [2, 5],
       [5, 5],
       [3, 4]])

In [51]:
(pd.DataFrame(rolls3)[0] == pd.DataFrame(rolls3)[1]).mean()

0.169

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [93]:
# heads = 1
# tails = 0
flips = np.random.choice([0, 1], size = (10000, 8))
flips

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0]])

In [96]:
flips_sums = flips.sum(axis = 1)

### Probability of exactly 3 heads.

In [99]:
(flips_sums == 3).mean()

0.2181

### Probability of > 3 heads.

In [100]:
(flips_sums > 3).mean()

0.6316

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [111]:
# 1, 2, 3 = WB
# 0 = DS
board1 = np.random.choice([0, 1, 1, 1], size = (10000, 1))
board1

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [112]:
board2 = np.random.choice([0, 1, 1, 1], size = (10000, 1))
board2

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [118]:
two_boards = board1 + board2
two_boards

array([[2],
       [1],
       [2],
       ...,
       [2],
       [2],
       [1]])

In [119]:
(two_boards == 0).mean()

0.0626

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values