## 1. How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
import pandas as pd

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 1

rolls1 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls1


array([[2],
       [2],
       [5],
       ...,
       [4],
       [1],
       [1]])

In [3]:
n_trials = nrows = 10_000
n_dice = ncols = 1

rolls2 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls2

array([[5],
       [3],
       [4],
       ...,
       [3],
       [4],
       [4]])

In [4]:
(rolls1 == rolls2).mean()

0.1636

In [5]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls3 = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls3

array([[2, 2],
       [3, 2],
       [1, 1],
       ...,
       [1, 5],
       [6, 4],
       [4, 2]])

In [6]:
(pd.DataFrame(rolls3)[0] == pd.DataFrame(rolls3)[1]).mean()

0.1729

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [7]:
# heads = 1
# tails = 0
flips = np.random.choice([0, 1], size = (10000, 8))
flips

array([[1, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 1, 0]])

In [8]:
flips_sums = flips.sum(axis = 1)

### Probability of exactly 3 heads.

In [9]:
(flips_sums == 3).mean()

0.2193

### Probability of > 3 heads.

In [10]:
(flips_sums > 3).mean()

0.64

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [90]:
# 1 = WB
# 0 = DS
board1 = np.random.choice([0, 1, 1, 1], size = (10000, 1))
board1

array([[1],
       [1],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [12]:
board2 = np.random.choice([0, 1, 1, 1], size = (10000, 1))
board2

array([[0],
       [1],
       [0],
       ...,
       [1],
       [1],
       [0]])

In [13]:
two_boards = board1 + board2
two_boards

array([[1],
       [2],
       [1],
       ...,
       [1],
       [2],
       [0]])

In [14]:
(two_boards == 0).mean()

0.0638

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [92]:
pop = np.random.normal(3, 1.5, size = (10000, 5))

In [95]:
(pop.sum(axis = 1) < 17).mean()

0.7254

## 5. Compare Heights
### - Men have an average height of 178 cm and standard deviation of 8cm.
### -Women have a mean of 170, sd = 6cm.
### -Since you have means and standard deviations, you can use np.random.normal to generate observations.
### - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [15]:
man = np.random.normal(178, 8, size = 10000)
man

array([186.72818699, 175.39094645, 180.08759695, ..., 165.29835974,
       183.8898256 , 184.03426755])

In [16]:
woman = np.random.normal(170, 6, size = 10000)
woman

array([172.94903038, 170.24671621, 164.02082395, ..., 173.59315727,
       168.56760543, 169.01845804])

In [17]:
((woman - man) > 0).mean()

0.2075

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [104]:
# 1 = corrupt
# 0 = good
sam = (np.random.choice([1, 0], p = [0.004, .996], size = (10000, 50)))
(sam.sum(axis = 1) == 0).mean()

0.8237

In [106]:
sam2 =(np.random.choice([1, 0], p = [0.004, .996], size = (10000, 100)))
(sam2.sum(axis = 1) == 0).mean()

0.6648

## What is the probability that we observe an installation issue within the first 150 students that download anaconda?



In [108]:
install = (np.random.choice([1, 0], p = [0.004, .996], size = (10000, 150)))

In [113]:
(install.sum(axis = 1) > 0).mean() 

0.4544

## How likely is it that 450 students all download anaconda without an issue?



In [110]:
install2 = (np.random.choice([1, 0], p = [0.004, .996], size = (10000,450)))

In [111]:
(install2.sum(axis = 1) == 0).mean()

0.1648

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [115]:
# .973 unlikely
# 0 = no food truck
# 1 = food truck
truck = (np.random.choice([1, 0], p = [0.7, .3], size = (10000, 3)))

In [118]:
prob = (truck.sum(axis = 1) == 0).mean()

In [120]:
unlikely = 1 - prob
unlikely

0.9724

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [121]:
def generate_random_bday():
    birthday = np.random.randint(1, num_possible_bdays)
    return birthday

def generate_k_birthdays(k):
    birthdays = [generate_random_bday() for _ in range(k)]
    return birthdays

def share(birthdays):
    unique_birthdays = set(birthdays)
    num_birthdays = len(birthdays)
    num_unique_birthdays = len(unique_birthdays)
    has_coincidence = (num_birthdays != num_unique_birthdays)
    return has_coincidence

def estimate_p_share(k):
    num_share = 0
    for _ in range(num_trials):
        birthdays = generate_k_birthdays(k)
        has_coincidence = aloc(birthdays)
        if has_coincidence:
            num_share += 1
    p_share = num_share / num_trials
    return p_share

In [122]:
estimate_p_share(23)

0.5078

In [88]:
estimate_p_share(20)

0.4123

In [89]:
estimate_p_share(40)

0.8899

In [123]:
bd = np.random.choice(range(1, 366), size = (10000, 23))

In [126]:
(pd.DataFrame(bd).nunique(axis = 1) < 23).mean()

0.501

In [ ]:
#np.random.choice(range(1,n_faces+1), n_die).sum(axis=1)